---
name: release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
          cache: maven
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
        with:
          global: true
          name: 'github'
          email: 'github@meeuw.org'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: mvn -Pdeploy --batch-mode  -Darguments=-DskipTests  release:prepare release:perform
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
